### ISSUE TITLE
Declarative Agent Error: "Manifest package validations failed. Declarative Copilot content violates Responsible AI guidelines"

### ISSUE THREAD

**Issue by rutviksatav** [microsoft/copilot-camp#427] opened 2024-12-09 13:31 UTC
# Declarative Agent Error: "Manifest package validations failed. Declarative Copilot content violates Responsible AI guidelines"

Hi everyone,

I’m working on the lab outlined in the following documentation: [Enhance Microsoft 365 Copilot with API Plugins](https://microsoft.github.io/copilot-camp/pages/extend-m365-copilot/04-enhance-api-plugin/).

While attempting to execute the `teamsApp/extendToM365` step, I encountered the following error:
  (×) Error: teamsApp/extendToM365 failed.
    (×) Error: Request failed with status code 400 (tracingId: 00-5a0b9db0e66b781bcf92c24ed93ea0af-4b56e029d497f56d-01) BadRequest: Manifest package validations failed. Errors: Declarative Copilot content violates Responsible AI guidelines; please review and resubmit. 

![Image](https://github.com/user-attachments/assets/749b2930-3ef8-45ef-bfe2-9d1232d23192)

## Questions:

1. Has anyone else encountered this error?
2. How can I adjust my manifest to comply with Responsible AI guidelines?
3. Are there additional resources or debugging steps for handling validation errors like this?

Thank you for your assistance!

**Comment by danielsnow29** [comment] 2024-12-11 21:28
I'm getting the same issue

**Comment by rabwill** [comment] 2024-12-15 22:12
Duplicate of https://github.com/microsoft/copilot-camp/issues/423

**Comment by rabwill** [comment] 2024-12-17 02:16
And update is pushed to the instructions to avoid RAI issue

**Closed by rabwill** 2024-12-17 02:16 UTC
