### ISSUE TITLE
Debug failed, Lab E2 - Step 5: Run the application

### ISSUE THREAD

**Issue by chenxizhang** [microsoft/copilot-camp#349] opened 2024-10-07 00:28 UTC
![image](https://github.com/user-attachments/assets/0ad26303-ffb7-4284-a1bc-f318ce2e9395)

**Comment by chenxizhang** [comment] 2024-10-07 00:28
[2024-10-07T00:25:21.444Z] [Info] - Finished 'Validate prerequisites' Visual Studio Code task in 1.73 seconds.
[2024-10-07T00:25:25.014Z] [Info] - Running Visual Studio Code task: 'Start local tunnel'

(Total: 1 Step) Teams Toolkit is starting local tunneling service to forward public URL to local port. Open the terminal window for details.

(1/1) Starting dev tunnel service ... 

Summary:

(√) Done: Forwarding URL https://35vlbspd-7071.asse.devtunnels.ms/ to http://localhost:7071 and saved [OPENAPI_SERVER_URL] to c:\Users\arechen\Downloads\trey-research\env\.env.local.

Visit https://aka.ms/teamsfx-local-tunnel-task to get more info about 'Start local tunnel' task.

[2024-10-07T00:25:26.147Z] [Info] - Started local tunneling service in 1.13 seconds.
[2024-10-07T00:25:26.319Z] [Info] - Executing provision 

Lifecycle stage: provision(5 step(s) in total). The following actions will be executed: 
(1/5) Action teamsApp/create: create Teams app.
(2/5) Action script
(3/5) Action teamsApp/zipAppPackage: build Teams app package.
(4/5) Action teamsApp/update: update Teams app.
(5/5) Action teamsApp/extendToM365: acquire Microsoft 365 title with the app package

[2024-10-07T00:25:26.321Z] [Info] - Executing lifecycle provision
[2024-10-07T00:25:27.208Z] [Info] -  [script stdout] "::set-teamsfx-env FUNC_NAME=me"; echo "::set-teamsfx-env FUNC_ENDPOINT=http://localhost:7071";

[2024-10-07T00:25:27.226Z] [Info] - (√)Done: Teams Package c:\Users\arechen\Downloads\trey-research\appPackage\build\appPackage.local.zip built successfully!
[2024-10-07T00:25:32.055Z] [Error] - Unable to execute action teamsApp/extendToM365. Error message: undefined
[2024-10-07T00:25:32.058Z] [Error] - Failed to Execute lifecycle provision due to failed action: teamsApp/extendToM365. PackageServiceError:Request failed with status code 400 (tracingId: 00-efb320b0b4e1ddfb66a48bf074ae2a1e-c69d036cc2956f25-01) BadRequest: No elements found in the manifest. . Env output: {"TEAMS_APP_ID":"204e3c33-ead6-4499-a4ef-4bc10c4dbf8e","TEAMS_APP_TENANT_ID":"72f988bf-86f1-41af-91ab-2d7cd011db47","FUNC_NAME":"me","FUNC_ENDPOINT":"http://localhost:7071","TEAMS_APP_UPDATE_TIME":"2024-10-07T00:25:29.6066389+00:00"}
[2024-10-07T00:25:32.060Z] [Info] - Execution summary:

Summary:
(×) Error: Lifecycle stage provision failed.
  (√) Done: teamsApp/create was executed successfully.
    (√) Done: Teams app with id 204e3c33-ead6-4499-a4ef-4bc10c4dbf8e already exists, skipped creating a new Teams app.
  (√) Done: script was executed successfully.
    (√) Done: Successfully executed command
  (√) Done: teamsApp/zipAppPackage was executed successfully.
  (√) Done: teamsApp/update was executed successfully.
    (√) Done: Teams app 204e3c33-ead6-4499-a4ef-4bc10c4dbf8e updated successfully
  (×) Error: teamsApp/extendToM365 failed.
    (×) Error: Request failed with status code 400 (tracingId: 00-efb320b0b4e1ddfb66a48bf074ae2a1e-c69d036cc2956f25-01) BadRequest: No elements found in the manifest.

**Comment by pkbullock** [comment] 2024-10-08 17:29
I'm seeing the same.

**Comment by cristianoag** [comment] 2024-10-08 17:39
I had that issue and it was caused by a reference to the trey-declarative-copilot.json file on the manifest. That reference should be there only after Lab3.

**Comment by BobGerman** [comment] 2024-10-08 23:46
Thanks for reporting, fixed in PR 359
https://github.com/microsoft/copilot-camp/pull/359

This happened because we had to remove the stand-alone API plugin since they are no longer supported, so Lab E2 became about learning and running just the API. The remaining manifest had no features, and Teams wouldn't install it. I could swear I tested but - who knows - anyway I added a static tab to the manifest in the E2 starter files to allow the app to deploy (it is never used). Then in E3 I added a new step to remove the static tab. Please LMK if you are still stuck but you should be able to do E3 and things should start working ...

**Closed by BobGerman** 2024-10-08 23:46 UTC
